// Motion-profile distance shares and GO_TO geometry.
// See docs/config/motion.md for what each governs.

export const REPEATED_CLICK_SPEED_MULTIPLIER = 5;
export const REPEATED_CLICK_ACCELERATION_DISTANCE_SHARE = 0.3;
export const REPEATED_CLICK_DECELERATION_DISTANCE_SHARE = 0.35;

export const GO_TO_TELEPORT_ENABLED = true;
export const GO_TO_PREFLIGHT_PAGE_SPAN = 1;
export const GO_TO_FINAL_APPROACH_PAGE_SPAN = 1;
export const GO_TO_TELEPORT_MIN_PAGE_SPAN = 3;
export const GO_TO_ACCELERATION_DISTANCE_SHARE = 0.35;
export const GO_TO_DECELERATION_DISTANCE_SHARE = 0.35;
export const GO_TO_SPEED_MULTIPLIER = 10;

export const STEP_ACCELERATION_DISTANCE_SHARE = 0.35;
export const STEP_DECELERATION_DISTANCE_SHARE = 0.4;

export const AUTOPLAY_ACCELERATION_DISTANCE_SHARE = 0.4;
export const AUTOPLAY_DECELERATION_DISTANCE_SHARE = 0.5;

export const SNAP_BACK_ACCELERATION_DISTANCE_SHARE = 0.08;
export const SNAP_BACK_DECELERATION_DISTANCE_SHARE = 0.7;
export const SNAP_BACK_DURATION_MS = 1300;
