export const CAROUSEL_DEFAULTS = {
  visibleSlidesNr: 3,
  durationAutoplay: 3000,
  intervalAutoplay: 3000,
  durationStep: 2000,
  jumpSpeedMultiplier: 8,
  errAltPlaceholder: "Downloading Error",
  isPagePaddingOn: false,
  isContentImg: true,
  isAuto: true,
  isPaginationOn: true,
  isControlsOn: true,
  isInteractive: true,
  isFinite: false,
} as const;
